name: pasanaku_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.2+1
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_file_downloader: ^1.2.1
  flutter_local_notifications: ^17.1.0
  go_router: ^13.2.2
  image_picker: ^1.1.0
  mobile_scanner: ^3.5.5
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/Bandera_Bolivia.png
    - assets/groupImg.png
    - assets/User_Icon.png
